name: soul Attack
on:
  push:
    paths-ignore:
      - 'soul'

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x *
    - run: sudo ./soul 127.0.0.1 80 1 999
